---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      repository: addon-hassio-repository-stable
      repository_edge: addon-hassio-repository-edge
      repository_beta: addon-hassio-repository-beta
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
