name: push_to_prod
on: 
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:  
    - name: Check out dev repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Publish Addon Image
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target proxy-manager
